Aminchukov/feature/loading
arturminchukov/beer-store pull request #10
Opened 2019-01-16 16:08 UTC by arturminchukov

#6

2019-01-16 16:09 UTC, arturminchukov commented
Тут коммиты из предыдущего пл реквеста еще приехали, так что сначала надо будет то мержить , потом ребейз делать

2019-01-22 10:01 UTC, AntonPashkowskiy requested changes

2019-01-22 10:01 UTC, AntonPashkowskiy commented on src/components/DetailsPage/DetailsPage.jsx
> +        if (beer) {
Чем меньше вложенностей - тем легче читать. Инвертируй выражение, пожалуйста. if(!beer) -> spinner

2019-01-22 10:07 UTC, AntonPashkowskiy approved these changes

2019-01-22 10:08 UTC, merged