Add beer details page
arturminchukov/beer-store pull request #7
Opened 2019-01-10 14:56 UTC by arturminchukov

2019-01-11 09:22 UTC, AntonPashkowskiy requested changes

2019-01-11 09:22 UTC, AntonPashkowskiy commented on src/components/BeerIngredient/BeerIngredient.jsx
> +            {`"${name}"`}
не понял этой конструкции. то есть понял но {name} всё равно короче

2019-01-11 09:22 UTC, AntonPashkowskiy commented on src/components/BeerIngredientList/BeerIngredientList.jsx
> +                            {ingredientClasses[ingredientType]
лучше сделать как можно больше логики снаружи разметки

2019-01-11 09:22 UTC, AntonPashkowskiy commented on src/components/BeerIngredientList/BeerIngredientList.jsx
> +                                {ingredient}
это можно вынести за скобки. а ещё лучше сделать фильтр перед map снаружи разметки.

2019-01-11 09:22 UTC, AntonPashkowskiy commented on src/components/BeerPropertyList/BeerPropertyList.jsx
> +                    abbr={beerProperty.abbr}
abbr -> abbreviation

2019-01-11 12:53 UTC, arturminchukov commented on src/components/BeerIngredient/BeerIngredient.jsx
> +            {`"${name}"`}
В этом моменте по формату нужны двойные ковычки, если их просто так ставить `sometext "{name}" sometext` , то тогда ругается eslint. и нужно делать что-то вроде через  &#8221;

2019-01-14 15:15 UTC, AntonPashkowskiy requested changes

2019-01-14 15:15 UTC, AntonPashkowskiy commented on src/components/BeerIngredientList/BeerIngredientList.jsx
> +    const ingredientTypeNames = Object.keys(ingredientTypes);
Совсем это пропустил. Почему это не массив? Почему компонент знает что это не массив? Зачем использовать словарь, если он здесь не подходит?

2019-01-14 15:15 UTC, AntonPashkowskiy commented on src/components/BeerIngredientList/BeerIngredientList.jsx
> +    const ingredientTypeNames = Object.keys(ingredientTypes);
Лучше передать массив ингридиентов и отрендерить его же.

2019-01-14 15:15 UTC, AntonPashkowskiy commented on src/components/BeerIngredientList/BeerIngredientList.jsx
> +export function BeerIngredientList({ingredientTypes = {}}) {
Если из файла импортируется один компонент, лучше его экспортировать по умолчанию. export default вместо export

2019-01-14 15:15 UTC, AntonPashkowskiy commented on src/components/BeerIngredientList/BeerIngredientList.jsx
> +export function BeerIngredientList({ingredientTypes = {}}) {
Для всех остальных то же самое

2019-01-14 15:15 UTC, AntonPashkowskiy commented on src/components/BeerPropertyList/BeerPropertyList.jsx
> +    const beerPropertiesList = Object.values(beerProperties);
То же самое. Никаких зависимостей от того что что-то где-то там хранится в JSON быть не должно.

2019-01-17 07:11 UTC, AntonPashkowskiy approved these changes

2019-01-17 07:11 UTC, merged